    DECLARE @daData nvarchar(10) = '01/01/1900'
	DECLARE @daCodArt nvarchar(50) = '000000'
	DECLARE @aCodArt nvarchar(50) = 'ZZZZZZZZ'
	DECLARE @fascia int = 0
	DECLARE @codCliente nvarchar(10) = '0301035'

	--AtexOCORDDDSA1.Text = DataControl1.Recordset!OCORDTDESS & " " & DataControl1.Recordset!OCORDTFORM & " " & DataControl1.Recordset!OCORDTLAL1 & " " & DataControl1.Recordset!OCORDTASL1 & IIf(DataControl1.Recordset!OCORDTLATE = "1", " (Ext.) ", " ") & DataControl1.Recordset!OCORDTLAL2 & " " & DataControl1.Recordset!OCORDTASL2 & IIf(DataControl1.Recordset!OCORDTLATE = "2", " (Ext.)", "")
 --   txtOCORDDRIFO.Text & " del " & txtOCORDDDRIO.Text

	--    'se fascia=0 allora sono formati
 --   If Val(txtOCORDDFASC.Text) = 0 Then
 --       txtOCORDDFASC.Text = txtOCORDDLUNF.Text & "x" & txtOCORDDLARF.Text
 --   End If

 --AtexOCORDDCART.Text = STquery("SELECT CAPRCL.CAPRCLSPEC FROM OCORDT INNER JOIN CAPRCL ON OCORDT.OCORDTCLIE = CAPRCL.CAPRCLCLIE AND OCORDT.OCORDTCCOM = CAPRCL.CAPRCLCODI WHERE (OCORDT.OCORDTNORD = " & IIf(IsNumeric(AtexOCORDDNORD.Text), AtexOCORDDNORD.Text, -1) & ")", "CAPRCLSPEC", "")
    asfd
    sfsaf
    asd
    fasd
    fas
    df
    asd
    fasd
    f
    asdf

    SELECT dbo.CalcoloPesoGrMq(OCORDDCART) AS PESOGRMQ, OCORDDNORD, OCORDDIRIG, OCORDDACLI, OCORDDRIFO, OCORDDDRIO, OCORDDNOTD, OCORDTDORD, OCORDTDESS, OCORDTFORM, OCORDTLAL1, OCORDTASL1, OCORDTLAL2, OCORDTASL2, OCORDTLATE, OCORDTUDMI, OCORDTCOAG, OCORDTTORD, OCORDTCLIE, OCORDTTDOC, OCORDDCART, OCORDTLPRE, OCORDDUDM1, OCORDDQTAD, OCORDDQDAE, OCORDDEVAS, OCORDDLUNF, OCORDDLARF, OCORDDFASC, OCORDDREFI, OCORDDCRIT, OCORDDCOMO, OCORDDGOFF, OCORDDCONP, OCORDDCONC, OCORDDDSA1, TBUDMI.TBUDMIORDC, TBUDMI_1.TBUDMISIGL, DATAEVASIONE.MaxOCORDEDTEV 
    --SELECT OCORDTNORD, OCORDTDORD, Convert(nvarchar(10), OCORDTDORD, 103) As dataOrdi, OCORDDCART, OCORDDACLI, OCORDDRIFO, OCORDDIRIG, OCORDTLPRE, OCORDDQTAD, OCORDDFASC, IsNull(OCORDTDESS, '') + ' ' + IsNull(OCORDTLAL1, '') + ' ' + IsNull(OCORDTLAL2, '') As descrizione, TBUDMISIGL
	FROM OCORDT INNER JOIN OCORDD ON OCORDTNORD = OCORDDNORD 
	INNER JOIN OCTORD ON OCORDTTORD = OCTORDCODI 
	INNER JOIN MAANAG ON OCORDDCART = MAANAGCODI
	INNER JOIN TBUDMI ON OCORDDUDM1 = TBUDMICODI  
	INNER JOIN OCSTAT ON OCORDTSTAT = OCSTATCODI 
	LEFT OUTER JOIN TBUDMI AS TBUDMI_1 ON OCORDTUDMI = TBUDMI_1.TBUDMICODI 
	LEFT JOIN (
		SELECT TOP (100) PERCENT OCORDENORD, OCORDEIRIG, MAX(OCORDEDTEV) AS MaxOCORDEDTEV 
		FROM OCORDE 
		GROUP BY OCORDENORD, OCORDEIRIG 
		ORDER BY MaxOCORDEDTEV DESC
	) AS DATAEVASIONE ON OCORDD.OCORDDNORD = DATAEVASIONE.OCORDENORD AND OCORDD.OCORDDIRIG = DATAEVASIONE.OCORDEIRIG 
    WHERE (OCORDTCLIE=@codCliente) AND (OCTORDSTAT='1') And (OCTORDBOLL='1') And (OCSTATSORD='1') And (OCORDDEVAS<>'S' Or OCORDDEVAS Is Null) And (OCORDDCONC>=@daData) And (OCORDDCART>=@daCodArt) And (OCORDD.OCORDDCART<=@aCodArt) And (OCORDD.OCORDDFASC>=@fascia) And (TBUDMI.TBUDMIORDC='1') 
	AND OCORDTNORD=44851
	ORDER BY OCORDTDORD

    --If Opzioni(8) <> "" Then stringaSQL = stringaSQL & " And (OCORDT.OCORDTLPRE='" & Opzioni(8) & "')"
    --If Opzioni(10) <> "" Then stringaSQL = stringaSQL & " And (OCORDD.OCORDDFASC<=" & Val(Opzioni(10)) & ")"
    --If Opzioni(17) <> "" Then stringaSQL = stringaSQL & " And (" & Opzioni(16) & "='" & Opzioni(17) & "')"
    --If Opzioni(3) <> "" Then stringaSQL = stringaSQL & " And (OCORDD.OCORDDCONC<=' " & Format(Opzioni(3), "dd/mm/yyyy") & "')"
    --stringaSQL = stringaSQL & ") Order by " & Opzioni(11) & ", " & Opzioni(12) & ", " & Opzioni(13) & ", " & Opzioni(14) & ", " & Opzioni(22) & ", " & Opzioni(24) & ";"
